import { cva } from "class-variance-authority";
/**
 * Pagination button variant styles using CVA
 */
export const paginationVariants = cva(
  [
    // Base styles
    "inline-flex",
    "items-center",
    "justify-center",
    "font-medium",
    "transition-all",
    "duration-300",
    "border",
    "select-none",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "disabled:opacity-50",
    "disabled:cursor-not-allowed",
    "disabled:pointer-events-none",
    "relative",
    "overflow-hidden",
    "isolate",
    "hover:scale-105",
    "active:scale-95",
  ],
  {
    variants: {
      variant: {
        default: [
          "bg-base-200",
          "text-base-content",
          "border-base-300",
          "hover:bg-base-300",
          "hover:shadow-lg",
          "focus:ring-primary",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary",
          "data-[active=true]:to-primary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-primary",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-primary/30",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-r",
          "before:from-transparent",
          "before:via-primary/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        primary: [
          "bg-primary/10",
          "text-primary",
          "border-primary/20",
          "hover:bg-primary/20",
          "hover:shadow-lg",
          "hover:shadow-primary/20",
          "focus:ring-primary",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary",
          "data-[active=true]:to-primary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-primary",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-primary/40",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-br",
          "before:from-primary/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        secondary: [
          "bg-secondary/10",
          "text-secondary",
          "border-secondary/20",
          "hover:bg-secondary/20",
          "hover:shadow-lg",
          "hover:shadow-secondary/20",
          "focus:ring-secondary",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-secondary",
          "data-[active=true]:to-secondary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-secondary",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-secondary/40",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-br",
          "before:from-secondary/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        accent: [
          "bg-accent/10",
          "text-accent",
          "border-accent/20",
          "hover:bg-accent/20",
          "hover:shadow-lg",
          "hover:shadow-accent/20",
          "focus:ring-accent",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-accent",
          "data-[active=true]:to-accent/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-accent",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-accent/40",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-br",
          "before:from-accent/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        ghost: [
          "bg-transparent",
          "text-base-content",
          "border-transparent",
          "hover:bg-base-content/5",
          "hover:shadow-sm",
          "focus:ring-base-content/20",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary",
          "data-[active=true]:to-primary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-primary",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-primary/30",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-r",
          "before:from-transparent",
          "before:via-primary/5",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        outlined: [
          "bg-transparent",
          "text-base-content",
          "border-base-content/20",
          "hover:bg-base-content/5",
          "hover:border-base-content/30",
          "hover:shadow-md",
          "focus:ring-base-content/20",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary",
          "data-[active=true]:to-primary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-primary",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-primary/30",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-br",
          "before:from-primary/5",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        minimal: [
          "bg-transparent",
          "text-base-content",
          "border-transparent",
          "hover:bg-base-200",
          "hover:shadow-md",
          "focus:ring-primary",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary",
          "data-[active=true]:to-primary/80",
          "data-[active=true]:!text-white",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-lg",
          "data-[active=true]:shadow-primary/30",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-r",
          "before:from-transparent",
          "before:via-primary/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
        glass: [
          "bg-white/5",
          "backdrop-blur-md",
          "text-foreground",
          "border-white/10",
          "hover:bg-white/10",
          "hover:border-white/20",
          "focus:ring-primary",
          "shadow-lg",
          "hover:shadow-xl",
          "hover:shadow-primary/20",
          "data-[active=true]:bg-gradient-to-br",
          "data-[active=true]:from-primary/80",
          "data-[active=true]:to-primary/60",
          "data-[active=true]:!text-white",
          "data-[active=true]:border-primary/50",
          "data-[active=true]:font-semibold",
          "data-[active=true]:shadow-xl",
          "data-[active=true]:shadow-primary/40",
          "before:absolute",
          "before:inset-0",
          "before:bg-gradient-to-br",
          "before:from-white/10",
          "before:to-transparent",
          "before:opacity-0",
          "hover:before:opacity-100",
          "before:transition-opacity",
          "before:duration-300",
        ],
      },
      size: {
        xs: ["h-6", "min-w-6", "px-1.5", "text-xs", "gap-0.5"],
        sm: ["h-8", "min-w-8", "px-2", "text-sm", "gap-1"],
        md: ["h-10", "min-w-10", "px-3", "text-base", "gap-1.5"],
        lg: ["h-12", "min-w-12", "px-4", "text-lg", "gap-2"],
        xl: ["h-14", "min-w-14", "px-5", "text-xl", "gap-2.5"],
        "2xl": ["h-16", "min-w-16", "px-6", "text-2xl", "gap-3"],
        "3xl": ["h-20", "min-w-20", "px-8", "text-3xl", "gap-4"],
        "4xl": ["h-24", "min-w-24", "px-10", "text-4xl", "gap-5"],
      },
      shape: {
        rounded: ["rounded-md"],
        square: ["rounded-none"],
        pill: ["rounded-full"],
        circle: ["rounded-full", "aspect-square"],
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
      shape: "rounded",
    },
  }
);
